
export const CATEGORIES = [
    {
        name: "Equipment",
        subcategories: [
            { name: "Dental Chairs", href: "/category/equipment?sub=Dental%20Chairs" },
            { name: "Radiology", href: "/category/equipment?sub=Radiology" },
            { name: "Sterilization", href: "/category/equipment?sub=Sterilization" },
            { name: "Laboratory", href: "/category/equipment?sub=Laboratory" },
            { name: "Surgical", href: "/category/equipment?sub=Surgical" },
        ],
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857683/media-hub/xfqsno4inozxgfvse8vk.jpg",
    },
    {
        name: "Instruments",
        subcategories: [
            { name: "Handsets", href: "/category/instruments?sub=Handsets" },
            { name: "Extraction", href: "/category/instruments?sub=Extraction" },
            { name: "Orthodontic", href: "/category/instruments?sub=Orthodontic" },
            { name: "General", href: "/category/instruments?sub=General" },
        ],
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857683/media-hub/xfqsno4inozxgfvse8vk.jpg",
    },
    {
        name: "Consumables",
        subcategories: [
            { name: "Gloves", href: "/category/consumables?sub=Gloves" },
            { name: "Masks", href: "/category/consumables?sub=Masks" },
            { name: "Disinfection", href: "/category/consumables?sub=Disinfection" },
            { name: "Impression", href: "/category/consumables?sub=Impression" },
        ],
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772858345/media-hub/dav3xfbxixoji4jbrlqh.webp",
    },
    {
        name: "Endodontics",
        subcategories: [
            { name: "Files", href: "/category/endodontics?sub=Files" },
            { name: "Sealers", href: "/category/endodontics?sub=Sealers" },
            { name: "Obturation", href: "/category/endodontics?sub=Obturation" },
            { name: "Apex Locators", href: "/category/endodontics?sub=Apex%20Locators" },
        ],
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857941/media-hub/b4bdxqamwhfwvnikx7ci.jpg",
    },
    {
        name: "Oral Care",
        subcategories: [
            { name: "Electric Brush", href: "/category/oral-care?sub=Electric%20Brush" },
            { name: "Manual Brushes", href: "/category/oral-care?sub=Manual%20Brushes" },
            { name: "Whitening Pastes", href: "/category/oral-care?sub=Whitening%20Pastes" },
            { name: "Specialized Care", href: "/category/oral-care?sub=Specialized%20Care" },
        ],
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772858132/media-hub/j0skz71hzszvfp4qewjy.jpg",
    },
    {
        name: "Eco-Sustainable",
        subcategories: [
            { name: "Recyclable", href: "/category/eco-sustainable?sub=Recyclable" },
            { name: "Biodegradable", href: "/category/eco-sustainable?sub=Biodegradable" },
            { name: "Refillable", href: "/category/eco-sustainable?sub=Refillable" },
        ],
        image: "/images/corn-starch-brushes.png",
    },
];


export const NAV_LINKS = [
    { name: "Oral Care", href: "/category/oral-care" },
    { name: "Eco-Sustainable", href: "/category/eco-sustainable" },
    { name: "Collection", href: "/collection" },
    { name: "Freebies", href: "/freebies", badge: "New" },
    { name: "Best Sellers", href: "/best-sellers" },
    { name: "Membership", href: "/membership" },
    { name: "Events", href: "/events" },
    { name: "New Clinic Setup", href: "/new-clinic-setup", special: true },
];

export const PRODUCTS = [
    {
        id: "p1",
        name: "Zenith Comfort Ergonomic Dental Chair",
        category: "Equipment",
        subCategory: "Dental Chairs",
        price: 185000,
        originalPrice: 210000,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857683/media-hub/xfqsno4inozxgfvse8vk.jpg",
        rating: 4.8,
        reviews: 124,
        inStock: true,
        features: ["LED Shadowless Light", "Fully Rotatable Ceramic Spittoon", "Wireless Foot control"],
        description: "Experience ultimate luxury and patient comfort with the Zenith Comfort Series. Award-winning ergonomics for the practitioner.",
    },
    {
        id: "p7",
        name: "Eco-Stream Compact Dental Unit",
        category: "Equipment",
        subCategory: "Dental Chairs",
        price: 110000,
        originalPrice: 135000,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857683/media-hub/xfqsno4inozxgfvse8vk.jpg",
        rating: 4.6,
        reviews: 45,
        inStock: true,
        features: ["Compact Design", "Standard Halogen Light", "Reliable Hydraulic Lift"],
        description: "Perfect for secondary clinics or specialized small operatory rooms. Durable and cost-effective.",
    },
    {
        id: "p2",
        name: "Precision-X Digital RVG Sensor",
        category: "Equipment",
        subCategory: "Radiology",
        price: 85000,
        originalPrice: 95000,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857941/media-hub/b4bdxqamwhfwvnikx7ci.jpg",
        rating: 4.9,
        reviews: 89,
        inStock: true,
    },
    {
        id: "p3",
        name: "B-Class High Pressure Autoclave",
        category: "Equipment",
        subCategory: "Sterilization",
        price: 45000,
        originalPrice: 52000,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772858345/media-hub/dav3xfbxixoji4jbrlqh.webp",
        rating: 4.7,
        reviews: 210,
        inStock: true,
    },
    {
        id: "p4",
        name: "Sonic Pro Electric Toothbrush",
        category: "Oral Care",
        subCategory: "Electric Brush",
        price: 3500,
        originalPrice: 4500,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772858132/media-hub/j0skz71hzszvfp4qewjy.jpg",
        rating: 4.9,
        reviews: 340,
        inStock: true,
    },
    {
        id: "p5",
        name: "Oral Care Advanced Toothpaste",
        category: "Oral Care",
        subCategory: "Whitening Pastes",
        price: 450,
        originalPrice: 600,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772858132/media-hub/j0skz71hzszvfp4qewjy.jpg",
        rating: 4.6,
        reviews: 150,
        inStock: true,
    },
    {
        id: "p6",
        name: "Pro-Series High Speed Handpiece",
        category: "Instruments",
        subCategory: "Handsets",
        price: 2500,
        originalPrice: 3200,
        image: "https://res.cloudinary.com/dmw5efwf5/image/upload/v1772857683/media-hub/xfqsno4inozxgfvse8vk.jpg",
        rating: 4.9,
        reviews: 56,
        inStock: true,
    },
];

export const TESTIMONIALS = [
    {
        id: 1,
        name: "Dr. Rajesh Gupta",
        role: "Senior Dentist, Mumbai",
        text: "Blueteeth Dental Store revolutionized how I source my clinic supplies. The delivery is super fast and products are 100% genuine.",
        rating: 5,
    },
    {
        id: 2,
        name: "Dr. Anjali Sharma",
        role: "Orthodontist, Delhi",
        text: "The 'New Clinic Setup' feature made setting up my second branch so easy. Highly recommended for all dental professionals.",
        rating: 5,
    },
    {
        id: 3,
        name: "Dr. Vikram Singh",
        role: "Endodontist, Bangalore",
        text: "Best prices in the market. I saved significantly on my annual equipment upgrade. Customer support is also very responsive.",
        rating: 4,
    },
];
